name: Foo

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

# permissions:
#   contents: write
#   id-token: write
#   packages: read
#   pull-requests: read

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.event.repository.default_branch }}

