name: Foo

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

permissions:
  pull-requests: read

jobs:

  chk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 20
    - uses: willbamford/monorepo-changed@v11
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
