name: Foo

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        # This may save additional git fetch roundtrip if
        # merge-base is found within latest 20 commits
        with:
          fetch-depth: 20

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          # list-files: json
          list-files: shell
          filters: |
            changed:
              - '**'

      - if: ${{ steps.changes.outputs.changed == 'true' }}
        run: for i in ${{ steps.changes.outputs.changed_files }}; do echo $i | awk ; done

  foo:
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: echo ${{ needs.changes.outputs.changed }}
      - run: echo ${{ needs.changes.outputs.changed_count }}
      - run: echo ${{ needs.changes.outputs.changed_files }}

  bar:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.changed == 'true' }}
    steps:
      - run: for i in ${{ needs.changes.outputs.changed_files }}; do echo $i | awk ; done