name: Foo

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          # list-files: json
          # list-files: json
          filters: |
            changed:
              - '**'

  show:
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.changes.outputs.changes }}
