name: Foo

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

permissions:
  pull-requests: read

jobs:

  chk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 20
    - uses: willbamford/monorepo-changed@v100
